version: 2

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - revive
    - gocritic
    - gosec
    - bodyclose

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0
